### ISSUE TITLE
Possible Undefined Task: 18.9.84.2

### ISSUE THREAD

**Issue by stridebn** [ansible-lockdown/Windows-2019-CIS#1]
TASK [/Users/brennans/Desktop/Work_Dir/win-2k19-cis : SCORED | 18.9.84.2 | PATCH | L1 Ensure Allow Windows Ink Workspace is set to Enabled On but disallow access above lock OR Disabled but not Enabled On] ***
fatal: [default]: FAILED! => {"msg": "The conditional check 'rule_18_9_84_2' failed. The error was: error while evaluating conditional (rule_18_9_84_2): 'rule_18_9_84_2' is undefined\n\nThe error appears to be in '/Users/brennans/Desktop/Work_Dir/win-2k19-cis/tasks/section18.yml': line 2312, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: "SCORED | 18.9.84.2 | PATCH | L1 Ensure Allow Windows Ink Workspace is set to Enabled On but disallow access above lock OR Disabled but not Enabled On"\n  ^ here\n"}

^ what I received during testing

**Comment by georgenalen** [comment]
I haven't been able to reproduce this one, so I'm going to close it for now
