### ISSUE TITLE
18.9.19.5 -  Ensure Turn off background refresh of Group Policy is set to Disabled

### ISSUE THREAD

**Issue by dennisharder-alight** [ansible-lockdown/Windows-2019-CIS#101]
**Describe the Issue**
CIS Rule 18.9.19.5 should be ensuring Group Policy background refreshes are not being disabled. The rule does not appear to be updating the right registry path and also the value appears wrong.
https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.GroupPolicy::DisableBackgroundPolicy

**Expected Behavior**
Group Policy background refreshes are not disabled.

**Actual Behavior**
No effect on Group Policy background refreshes being enabled or disabled.

**Control(s) Affected**
18.9.19.5

**Environment (please complete the following information):**
- 2.0.0

**Additional Notes**
Anything additional goes here

**Possible Solution**
The following registry value should be 0 (or removed).
`
- name: "18.9.19.5 | PATCH | Ensure Turn off background refresh of Group Policy is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System <-- REMOVED 'DisableBkGndGroupPolicy'
      name: DisableBkGndGroupPolicy
      data: 1                                          <-- CHANGE THIS TO 0
      type: dword
  when:
      - win19cis_rule_18_9_19_5
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_18.9.19.5
      - patch
      - gpo
`

**Comment by frederickw082922** [comment]
Thank you @dennisharder-alight ! Good catch!! Thank you submitting the Issue!

**Comment by MrSteve81** [comment]
Pushed to Devel.
