### ISSUE TITLE
A tag on control 2.3.1.5 is incorrect

### ISSUE THREAD

**Issue by devallan** [ansible-lockdown/Windows-2019-CIS#104]
The tags on control 2.3.1.5 for **both Windows 2019 and 2022** pluralize 'memberserver' to 'memberservers'. As a result, the playbook will not run the control when the tag 'level1-memberserver' is specified.

  tags:
      - level1-domaincontroller
      - **level1-memberservers**
      - rule_2.3.1.5
      - patch
      - securitypolicy

should be

  tags:
      - level1-domaincontroller
      - **level1-memberserver**
      - rule_2.3.1.5
      - patch
      - securitypolicy

**Comment by MrSteve81** [comment]
Will be adding this to a fix im working on today.  Thanks @devallan

**Comment by MrSteve81** [comment]
Pushed to Devel.
