### ISSUE TITLE
Rule 1.1.4 and 1.1.6

### ISSUE THREAD

**Issue by animatco** [ansible-lockdown/Windows-2019-CIS#105]
**Describe the Issue**
If the "RelaxMinimumPasswordLengthLimits" is not set prior to the "MinimumPasswordLength" an error occurs if the password is set beyond 14 characters.

**Expected Behavior**
Minimum Password length larger than 14 Characters is allowed 

**Actual Behavior**
Ansible Errors when attempting to set, with a missing secedit.ini file error.

**Control(s) Affected**
Rule 1.1.4 and 1.1.6

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.16.3
- Host Python Version: 3.12.3 
- Ansible Server Python Version: 3.12.3 
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
change order of run so that 1.1.6 runs 1st then 1.1.4

**Comment by MrSteve81** [comment]
Thanks for the finding in working on the new release 3.0.1 they have removed this but i will look into updating the one currently in devel here.

**Comment by MrSteve81** [comment]
Working on fix today to have into a branch

**Comment by MrSteve81** [comment]
Pushed to Devel.
