### ISSUE TITLE
Controls 2.3.1.5 and 2.3.1.6 use hardcoded values instead of variables

### ISSUE THREAD

**Issue by bschapendonk** [ansible-lockdown/Windows-2019-CIS#40]
https://github.com/ansible-lockdown/Windows-2019-CIS/blob/devel/tasks/section02.yml#L703

`value: GeorgeSharp` instead of `value: '{{ newadministratorname }}'`

https://github.com/ansible-lockdown/Windows-2019-CIS/blob/devel/tasks/section02.yml#L721

`value: BobCooper` instead of `value: '{{ renamedguest}}'`

**Comment by georgenalen** [comment]
Addressed in PR #44 release 1.1.1
