### ISSUE TITLE
2.2.18 Only works if the Hyper-V Role is installed

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [ansible-lockdown/Windows-2019-CIS#42]
2.2.18 will assume that the "NT VIRTUAL MACHINE\Virtual Machines" group exist (although it should only exist when the Hyper-V role is installed).

If it does not exist, it will error. There should be a check to make sure that the "NT VIRTUAL MACHINE\Virtual Machines" group exists before performing the rest of the task

**Comment by georgenalen** [comment]
Addressed in PR #44 release 1.1.1
