### ISSUE TITLE
18.5.10.2 

### ISSUE THREAD

**Issue by Julieeeen** [ansible-lockdown/Windows-2019-CIS#47]
wrong level for the control 18.5.10.2 , it's normally a L2 but the tag is with L1

- name: "SCORED | 18.5.10.2 | PATCH | L2 Ensure Turn off Microsoft Peer-to-Peer Networking Services is set to Enabled"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Peernet
      name: Disabled
      data: 1
      type: dword
  when:
      - rule_18_5_10_2
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_18.5.10.2
      - patch

**Comment by uk-bolly** [comment]
Hi @Julieeeen 

Thank you for taking the time to raise these issues, it is only through feedback we can improve these. Apologies for the delay in responding other priorities came through. We are looking to have more time to keep up with the changes in these benchmarks and feedback going forward.
This was merged later last year and hopefully all as expected?

Thank you once again

uk-bolly
