### ISSUE TITLE
2.2.33 fails on Windows 2019 Server Core

### ISSUE THREAD

**Issue by oatakan** [ansible-lockdown/Windows-2019-CIS#48]
Window Manager\Window Manager Group only exists on non Core installations. When running on a Windows 2019 Core system, task 2.2.33 fails complaining Window Manager does not exists.

**Comment by georgenalen** [comment]
@oatakan,
 This is in the cis_1.2.1_and_updates branch. It's slightly different than your PR for this but very similar and does the same thing. I will close out that PR. It will make it's way into devel/main in the next couple of weeks. 

-George
