### ISSUE TITLE
ansible_windows_domain_role' is undefined

### ISSUE THREAD

**Issue by dimi4ik** [ansible-lockdown/Windows-2019-CIS#64]
**Describe the Issue**

When I run the role, I receive the following message:

`TASK [Windows-2019-CIS : Include the preliminary tasks] ***********************************************************************************************************************************************************************************************************************
included: /home/azureuser/github/projekt_AnsibleLernen/azurelab/roles/Windows-2019-CIS/tasks/prelim.yml for apc000060002

TASK [Windows-2019-CIS : Set fact is system is standalone] ********************************************************************************************************************************************************************************************************************
fatal: [apc000060002]: FAILED! => 
  msg: |-
    The conditional check 'ansible_windows_domain_role ==  'Stand-alone server'' failed. The error was: error while evaluating conditional (ansible_windows_domain_role ==  'Stand-alone server'): 'ansible_windows_domain_role' is undefined
  
    The error appears to be in '/home/azureuser/github/projekt_AnsibleLernen/azurelab/roles/Windows-2019-CIS/tasks/prelim.yml': line 5, column 9, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
      block:
          - name: Set fact is system is standalone
            ^ here`
  
    The offending line appears to be:
  
      block:
          - name: Set fact is system is standalone
            ^ here`

**Expected Behavior**
The task should process correctly for a domain joined machine

**Actual Behavior**
A clear and concise description of what's happening.

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**
 - git branch: [e.g devel]
 - Ansible Version: [e.g. 2.10] 
 - Host Python Version: [e.g. Python 3.7.6]
 - Ansible Server Python Version: [e.g. Python 3.7.6]
 - Additional Details:

**Additional Notes**
am I doing something wrong ? thanks for the ti

**Possible Solution**
Enter a suggested fix here

**Comment by dimi4ik** [comment]
can be fixed, the playbook must contain:

`gather_facts: true`

**Comment by dimi4ik** [comment]
can be fixed, the playbook must contain:

gather_facts: true

**Comment by uk-bolly** [comment]
hi @dimi4ik 

Thank you for the feedback, i believe gather_facts: true is the default value. So should be run unless explicitly turned to false or defaults overridden in the loaded ansible.cfg

I will however leave this issue open to ensure we add that to the playbook, in the next release.

Thank you again for the feedback

uk-bolly

**Comment by MrSteve81** [comment]
Will be added to the upcoming release in the playbook. I have assigned this to myself to add in my next release.

**Comment by MrSteve81** [comment]
Complete and merged to devel.
