### ISSUE TITLE
18.3.7 control is missing

### ISSUE THREAD

**Issue by Julieeeen** [ansible-lockdown/Windows-2019-CIS#7]
Looks like the Control 18.3.7 is missing in the task definition

**Comment by georgenalen** [comment]
This one is addressed with the latest release, v1.0.1. For some reason 18.3.6 was actually 18.3.7 in the role making 18.3.6 as the missing one. So I sorted that out and you now have all of the controls in there. I'm not sure how that one was missed....

George
