### ISSUE TITLE
Not able to RDP after hardening of Windows server 2019 OS

### ISSUE THREAD

**Issue by vivekbangare** [ansible-lockdown/Windows-2019-CIS#87]
**Question**
After applying for WINDOWS-2019-CIS roles(devel branch), I cannot RDP after the reboot of Windows server 2019, what would you need to do to fix the issue?

**Environment:**

- Ansible Version: [ 2.14.6 ]
- Host Python Version: [ Python 3.9.18 ]
- Ansible Server Python Version: [ Python 3.9.18 ]
- Additional Details: I am creating golden image AMI with the help of WINDOWS-2019-CIS roles, but as soon as all tasks are completed and I restart the machine, I cannot log in to my new machine.
- The reboot_windows handler doesn't work, it's stuck always, hence I have commented handler and then tested it.

Note: I have set win19cis_rule_18_10_57_3_9_3 to false from defaults/main.yml , still facing the same issue.

**Comment by MrSteve81** [comment]
@vivekbangare Good day and thank you for raising your question.  Upon the creation of these roles we have found a number of different issues with RDP and WinRM when applying the CIS. In our testing of the roles we have a variable that we use that we set to true to skip the tasks we have identified that cause these breaking changes.  Set the following variable then you can backwards work the listed controls to see which are causing the issues.  It could likely be a firewall rule here.  
win_skip_for_test: true

**Comment by frederickw082922** [comment]
Good day @vivekbangare ! Any update?

**Comment by frederickw082922** [comment]
No follow-up response from @vivekbangare ! Closing #87
