### ISSUE TITLE
Rule 18.9.50.1.2 (L2) Ensure 'Enable Windows NTP Server' is set to 'Disabled' (MS only)

### ISSUE THREAD

**Issue by animatco** [ansible-lockdown/Windows-2019-CIS#90]
**Describe the Issue**
If manually set using GPEDIT correct value is 0

**Expected Behavior**
value set to 0

**Actual Behavior**
value set to 1

**Control(s) Affected**
Rule 18.9.50.1.2 (L2) Ensure 'Enable Windows NTP Server' is set to 'Disabled' (MS only)

**Environment (please complete the following information):**

- branch being used: devel

**Possible Solution**
- name: "18.9.50.1.2 | PATCH | Ensure Enable Windows NTP Server is set to Disabled MS only | Member Server"
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\W32Time\Timeproviders\Ntpserver
        name: Enabled
        data: 0
        type: dword
      when:
        - win19cis_rule_18_9_50_1_2
        - win2019cis_is_domain_member
      tags:
        - level2-memberserver
        - rule_18.9.50.1.2
        - patch
        - ntp

**Comment by frederickw082922** [comment]
Thank you @animatco ! Good Catch! 

https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsTimeService::W32TIME_POLICY_ENABLE_NTPSERVER

CC: @MrSteve81
