### ISSUE TITLE
Rule 18.6.4.2 (L1) Ensure 'Turn off multicast name resolution' is set to 'Enabled'

### ISSUE THREAD

**Issue by animatco** [ansible-lockdown/Windows-2019-CIS#91]
**Describe the Issue**
If manually set using GPEDIT correct value is 0

**Expected Behavior**
value set to 0

**Actual Behavior**
value set to 1

**Control(s) Affected**
"18.6.4.2 | PATCH | Ensure Turn off multicast name resolution is set to Enabled MS Only | Member Server"

**Environment (please complete the following information):**

- branch being used: [devel]

**Possible Solution**
    - name: "18.6.4.2 | PATCH | Ensure Turn off multicast name resolution is set to Enabled MS Only | Member Server"
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows NT\DNSClient
        name: EnableMulticast
        data: 0
        type: dword
      when:
        - win19cis_rule_18_6_4_2
        - win2019cis_is_domain_member
      tags:
        - level1-domaincontroller
        - level1-memberserver
        - rule_18.6.4.3
        - patch
        - dns

**Comment by frederickw082922** [comment]
Good catch @animatco  !! 

https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.DNSClient::Turn_Off_Multicast

Thank you!

CC: @MrSteve81

**Comment by frederickw082922** [comment]
Fix merged in #95
