### ISSUE TITLE
Rule 18.7.2 (L1) Ensure 'Configure Redirection Guard' is set to 'Enabled: Redirection Guard Enabled'

### ISSUE THREAD

**Issue by animatco** [ansible-lockdown/Windows-2019-CIS#92]
**Describe the Issue**
If manually set using GPEDIT correct value is 1

**Expected Behavior**
value set to 1

**Actual Behavior**
value set to 2

**Control(s) Affected**
"18.7.2 | PATCH | Ensure Configure Redirection Guard is set to Enabled Redirection Guard Enabled"

**Environment (please complete the following information):**

- branch being used:  devel

**Possible Solution**
    - name: "18.7.2 | PATCH | Ensure Configure Redirection Guard is set to Enabled Redirection Guard Enabled"
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers
        name: RedirectionguardPolicy
        data: 1
        type: dword
      when:
        - win19cis_rule_18_7_2
      tags:
        - level1-domaincontroller
        - level2-memberserver
        - rule_18.7.2
        - patch
        - printers

**Comment by frederickw082922** [comment]
Good catch @animatco  

[RedirectionguardPolicy](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-printers#configureredirectionguardpolicy)

Thank you!

CC: @MrSteve81

**Comment by frederickw082922** [comment]
Fix merged in #95
