### ISSUE TITLE
Rule 5.1/5.2 | PATCH | Ensure Print Spooler (Spooler) is set to ... - Invalid Tag

### ISSUE THREAD

**Issue by dennisharder-alight** [ansible-lockdown/Windows-2019-CIS#94]
**Describe the Issue**
A tag associated with the rule appears to have a typo.

**Expected Behavior**
The tag **level2-domainmember** should be **level2-memberserver**

**Actual Behavior**
Wrong tag applied

**Control(s) Affected**
Unable to either run or skip 5.1/5.2 via appropriate tag.

**Environment (please complete the following information):**
Release 2.0.0

**Additional Notes**
According to readme, the following tags are available to control CIS level.
- level1-domaincontroller
- level1-memberserver
- level2-domaincontroller
- level2-memberserver

**Possible Solution**
Change the tag to level2-memberserver

- name: |
    "5.1 | PATCH | Ensure Print Spooler (Spooler) is set to Disabled Domain Controller &
     5.2 | PATCH | Ensure Print Spooler (Spooler) is set to Disabled Member Server"
  block:
...
  tags:
      - level1-domaincontroller
      - ~~level2-domainmember~~ level2-memberserver

**Comment by frederickw082922** [comment]
Good catch @dennisharder-alight  !!

We will review!

Thank you!!

CC: @MrSteve81

**Comment by frederickw082922** [comment]
Fix merged in #95
