### ISSUE TITLE
Rule 18.7.2-18.7.7 : Invalid Tags - Level 1 CIS

### ISSUE THREAD

**Issue by dennisharder-alight** [ansible-lockdown/Windows-2019-CIS#96]
**Describe the Issue**
According to the Windows 2019 CIS benchmarks, rules 18.7.2-18.7.7 are part of CIS level1. These are currently set to level2.

**Expected Behavior**
The tag **level2-memberserver** should be **level1-memberserver**

**Actual Behavior**
Wrong tag applied

**Control(s) Affected**
18.7.2-18.7.7

**Environment (please complete the following information):**
Release 2.0.0

**Additional Notes**
Attaching CIS Benchmark
[CIS_Microsoft_Windows_Server_2019_Benchmark_v2.0.0.pdf](https://github.com/ansible-lockdown/Windows-2019-CIS/files/14514690/CIS_Microsoft_Windows_Server_2019_Benchmark_v2.0.0.pdf)

**Possible Solution**
Change the tag to level1-memberserver

**Comment by frederickw082922** [comment]
Thank you @dennisharder-alight !

Great find! 

CC: @MrSteve81

**Comment by frederickw082922** [comment]
Fix merged in #95
